/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Geometry
{
    public class Quaternion : Message
    {
        public const string RosMessageName = "geometry_msgs/msg/Quaternion";

        //  This represents an orientation in free space in quaternion form.
        public const double x = 0;
        public const double y = 0;
        public const double z = 0;
        public const double w = 1;

        public Quaternion()
        {
        }
    }
}
#endif
