/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Pendulum
{
    public class JointState : Message
    {
        public const string RosMessageName = "pendulum_msgs/msg/JointState";

        public double position { get; set; }
        public double velocity { get; set; }
        public double effort { get; set; }

        public JointState()
        {
            this.position = 0.0;
            this.velocity = 0.0;
            this.effort = 0.0;
        }

        public JointState(double position, double velocity, double effort)
        {
            this.position = position;
            this.velocity = velocity;
            this.effort = effort;
        }
    }
}
#endif
