/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

using RosSharp.RosBridgeClient.MessageTypes.BuiltinInterfaces;

namespace RosSharp.RosBridgeClient.MessageTypes.Pendulum
{
    public class RttestResults : Message
    {
        public const string RosMessageName = "pendulum_msgs/msg/RttestResults";

        public Time stamp { get; set; }
        public JointCommand command { get; set; }
        public JointState state { get; set; }
        public ulong cur_latency { get; set; }
        public double mean_latency { get; set; }
        public ulong min_latency { get; set; }
        public ulong max_latency { get; set; }
        public ulong minor_pagefaults { get; set; }
        public ulong major_pagefaults { get; set; }

        public RttestResults()
        {
            this.stamp = new Time();
            this.command = new JointCommand();
            this.state = new JointState();
            this.cur_latency = 0;
            this.mean_latency = 0.0;
            this.min_latency = 0;
            this.max_latency = 0;
            this.minor_pagefaults = 0;
            this.major_pagefaults = 0;
        }

        public RttestResults(Time stamp, JointCommand command, JointState state, ulong cur_latency, double mean_latency, ulong min_latency, ulong max_latency, ulong minor_pagefaults, ulong major_pagefaults)
        {
            this.stamp = stamp;
            this.command = command;
            this.state = state;
            this.cur_latency = cur_latency;
            this.mean_latency = mean_latency;
            this.min_latency = min_latency;
            this.max_latency = max_latency;
            this.minor_pagefaults = minor_pagefaults;
            this.major_pagefaults = major_pagefaults;
        }
    }
}
#endif
