/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Turtlesim
{
    public class Color : Message
    {
        public const string RosMessageName = "turtlesim/msg/Color";

        public byte r { get; set; }
        public byte g { get; set; }
        public byte b { get; set; }

        public Color()
        {
            this.r = 0;
            this.g = 0;
            this.b = 0;
        }

        public Color(byte r, byte g, byte b)
        {
            this.r = r;
            this.g = g;
            this.b = b;
        }
    }
}
#endif
