/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Turtlesim
{
    public class Pose : Message
    {
        public const string RosMessageName = "turtlesim/msg/Pose";

        public float x { get; set; }
        public float y { get; set; }
        public float theta { get; set; }
        public float linear_velocity { get; set; }
        public float angular_velocity { get; set; }

        public Pose()
        {
            this.x = 0.0f;
            this.y = 0.0f;
            this.theta = 0.0f;
            this.linear_velocity = 0.0f;
            this.angular_velocity = 0.0f;
        }

        public Pose(float x, float y, float theta, float linear_velocity, float angular_velocity)
        {
            this.x = x;
            this.y = y;
            this.theta = theta;
            this.linear_velocity = linear_velocity;
            this.angular_velocity = angular_velocity;
        }
    }
}
#endif
