/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Ur
{
    public class Digital : Message
    {
        public const string RosMessageName = "ur_msgs/msg/Digital";

        public byte pin { get; set; }
        public bool state { get; set; }

        public Digital()
        {
            this.pin = 0;
            this.state = false;
        }

        public Digital(byte pin, bool state)
        {
            this.pin = pin;
            this.state = state;
        }
    }
}
#endif
