/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Ur
{
    public class IOStates : Message
    {
        public const string RosMessageName = "ur_msgs/msg/IOStates";

        public Digital[] digital_in_states { get; set; }
        public Digital[] digital_out_states { get; set; }
        public Digital[] flag_states { get; set; }
        public Analog[] analog_in_states { get; set; }
        public Analog[] analog_out_states { get; set; }

        public IOStates()
        {
            this.digital_in_states = new Digital[0];
            this.digital_out_states = new Digital[0];
            this.flag_states = new Digital[0];
            this.analog_in_states = new Analog[0];
            this.analog_out_states = new Analog[0];
        }

        public IOStates(Digital[] digital_in_states, Digital[] digital_out_states, Digital[] flag_states, Analog[] analog_in_states, Analog[] analog_out_states)
        {
            this.digital_in_states = digital_in_states;
            this.digital_out_states = digital_out_states;
            this.flag_states = flag_states;
            this.analog_in_states = analog_in_states;
            this.analog_out_states = analog_out_states;
        }
    }
}
#endif
