/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Ur
{
    public class MasterboardDataMsg : Message
    {
        public const string RosMessageName = "ur_msgs/msg/MasterboardDataMsg";

        //  This data structure contains the MasterboardData structure
        //  used by the Universal Robots controller
        // 
        //  MasterboardData is part of the data structure being send on the
        //  secondary client communications interface
        //  
        //  This data structure is send at 10 Hz on TCP port 30002
        //  
        //  Documentation can be found on the Universal Robots Support site, article
        //  number 16496.
        public uint digital_input_bits { get; set; }
        public uint digital_output_bits { get; set; }
        public sbyte analog_input_range0 { get; set; }
        public sbyte analog_input_range1 { get; set; }
        public double analog_input0 { get; set; }
        public double analog_input1 { get; set; }
        public sbyte analog_output_domain0 { get; set; }
        public sbyte analog_output_domain1 { get; set; }
        public double analog_output0 { get; set; }
        public double analog_output1 { get; set; }
        public float masterboard_temperature { get; set; }
        public float robot_voltage_48v { get; set; }
        public float robot_current { get; set; }
        public float master_io_current { get; set; }
        public byte master_safety_state { get; set; }
        public byte master_onoff_state { get; set; }

        public MasterboardDataMsg()
        {
            this.digital_input_bits = 0;
            this.digital_output_bits = 0;
            this.analog_input_range0 = 0;
            this.analog_input_range1 = 0;
            this.analog_input0 = 0.0;
            this.analog_input1 = 0.0;
            this.analog_output_domain0 = 0;
            this.analog_output_domain1 = 0;
            this.analog_output0 = 0.0;
            this.analog_output1 = 0.0;
            this.masterboard_temperature = 0.0f;
            this.robot_voltage_48v = 0.0f;
            this.robot_current = 0.0f;
            this.master_io_current = 0.0f;
            this.master_safety_state = 0;
            this.master_onoff_state = 0;
        }

        public MasterboardDataMsg(uint digital_input_bits, uint digital_output_bits, sbyte analog_input_range0, sbyte analog_input_range1, double analog_input0, double analog_input1, sbyte analog_output_domain0, sbyte analog_output_domain1, double analog_output0, double analog_output1, float masterboard_temperature, float robot_voltage_48v, float robot_current, float master_io_current, byte master_safety_state, byte master_onoff_state)
        {
            this.digital_input_bits = digital_input_bits;
            this.digital_output_bits = digital_output_bits;
            this.analog_input_range0 = analog_input_range0;
            this.analog_input_range1 = analog_input_range1;
            this.analog_input0 = analog_input0;
            this.analog_input1 = analog_input1;
            this.analog_output_domain0 = analog_output_domain0;
            this.analog_output_domain1 = analog_output_domain1;
            this.analog_output0 = analog_output0;
            this.analog_output1 = analog_output1;
            this.masterboard_temperature = masterboard_temperature;
            this.robot_voltage_48v = robot_voltage_48v;
            this.robot_current = robot_current;
            this.master_io_current = master_io_current;
            this.master_safety_state = master_safety_state;
            this.master_onoff_state = master_onoff_state;
        }
    }
}
#endif
