/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Ur
{
    public class RobotModeDataMsg : Message
    {
        public const string RosMessageName = "ur_msgs/msg/RobotModeDataMsg";

        //  This data structure contains the RobotModeData structure
        //  used by the Universal Robots controller
        // 
        //  This data structure is send at 10 Hz on TCP port 30002
        // 
        //  Note: this message does not carry all fields from the RobotModeData structure as broadcast by the robot controller, but a subset.
        public ulong timestamp { get; set; }
        public bool is_robot_connected { get; set; }
        public bool is_real_robot_enabled { get; set; }
        public bool is_power_on_robot { get; set; }
        public bool is_emergency_stopped { get; set; }
        public bool is_protective_stopped { get; set; }
        public bool is_program_running { get; set; }
        public bool is_program_paused { get; set; }

        public RobotModeDataMsg()
        {
            this.timestamp = 0;
            this.is_robot_connected = false;
            this.is_real_robot_enabled = false;
            this.is_power_on_robot = false;
            this.is_emergency_stopped = false;
            this.is_protective_stopped = false;
            this.is_program_running = false;
            this.is_program_paused = false;
        }

        public RobotModeDataMsg(ulong timestamp, bool is_robot_connected, bool is_real_robot_enabled, bool is_power_on_robot, bool is_emergency_stopped, bool is_protective_stopped, bool is_program_running, bool is_program_paused)
        {
            this.timestamp = timestamp;
            this.is_robot_connected = is_robot_connected;
            this.is_real_robot_enabled = is_real_robot_enabled;
            this.is_power_on_robot = is_power_on_robot;
            this.is_emergency_stopped = is_emergency_stopped;
            this.is_protective_stopped = is_protective_stopped;
            this.is_program_running = is_program_running;
            this.is_program_paused = is_program_paused;
        }
    }
}
#endif
