/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.Ur
{
    public class ToolDataMsg : Message
    {
        public const string RosMessageName = "ur_msgs/msg/ToolDataMsg";

        //  This data structure contains the ToolData structure
        //  used by the Universal Robots controller
        public const sbyte ANALOG_INPUT_RANGE_CURRENT = 0;
        public const sbyte ANALOG_INPUT_RANGE_VOLTAGE = 1;
        public sbyte analog_input_range2 { get; set; }
        //  one of ANALOG_INPUT_RANGE_*
        public sbyte analog_input_range3 { get; set; }
        //  one of ANALOG_INPUT_RANGE_*
        public double analog_input2 { get; set; }
        public double analog_input3 { get; set; }
        public float tool_voltage_48v { get; set; }
        public byte tool_output_voltage { get; set; }
        public float tool_current { get; set; }
        public float tool_temperature { get; set; }
        public const byte TOOL_BOOTLOADER_MODE = 249;
        public const byte TOOL_RUNNING_MODE = 253;
        public const byte TOOL_IDLE_MODE = 255;
        public byte tool_mode { get; set; }
        //  one of TOOL_*

        public ToolDataMsg()
        {
            this.analog_input_range2 = 0;
            this.analog_input_range3 = 0;
            this.analog_input2 = 0.0;
            this.analog_input3 = 0.0;
            this.tool_voltage_48v = 0.0f;
            this.tool_output_voltage = 0;
            this.tool_current = 0.0f;
            this.tool_temperature = 0.0f;
            this.tool_mode = 0;
        }

        public ToolDataMsg(sbyte analog_input_range2, sbyte analog_input_range3, double analog_input2, double analog_input3, float tool_voltage_48v, byte tool_output_voltage, float tool_current, float tool_temperature, byte tool_mode)
        {
            this.analog_input_range2 = analog_input_range2;
            this.analog_input_range3 = analog_input_range3;
            this.analog_input2 = analog_input2;
            this.analog_input3 = analog_input3;
            this.tool_voltage_48v = tool_voltage_48v;
            this.tool_output_voltage = tool_output_voltage;
            this.tool_current = tool_current;
            this.tool_temperature = tool_temperature;
            this.tool_mode = tool_mode;
        }
    }
}
#endif
