/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UrDashboard
{
    public class RobotMode : Message
    {
        public const string RosMessageName = "ur_dashboard_msgs/msg/RobotMode";

        public const sbyte NO_CONTROLLER = -1;
        public const sbyte DISCONNECTED = 0;
        public const sbyte CONFIRM_SAFETY = 1;
        public const sbyte BOOTING = 2;
        public const sbyte POWER_OFF = 3;
        public const sbyte POWER_ON = 4;
        public const sbyte IDLE = 5;
        public const sbyte BACKDRIVE = 6;
        public const sbyte RUNNING = 7;
        public const sbyte UPDATING_FIRMWARE = 8;
        public sbyte mode { get; set; }

        public RobotMode()
        {
            this.mode = 0;
        }

        public RobotMode(sbyte mode)
        {
            this.mode = mode;
        }
    }
}
#endif
