/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */

#if ROS2

namespace RosSharp.RosBridgeClient.MessageTypes.UrDashboard
{
    public class SafetyMode : Message
    {
        public const string RosMessageName = "ur_dashboard_msgs/msg/SafetyMode";

        public const byte NORMAL = 1;
        public const byte REDUCED = 2;
        public const byte PROTECTIVE_STOP = 3;
        public const byte RECOVERY = 4;
        public const byte SAFEGUARD_STOP = 5;
        public const byte SYSTEM_EMERGENCY_STOP = 6;
        public const byte ROBOT_EMERGENCY_STOP = 7;
        public const byte VIOLATION = 8;
        public const byte FAULT = 9;
        public const byte VALIDATE_JOINT_ID = 10;
        public const byte UNDEFINED_SAFETY_MODE = 11;
        public const byte AUTOMATIC_MODE_SAFEGUARD_STOP = 12;
        public const byte SYSTEM_THREE_POSITION_ENABLING_STOP = 13;
        public byte mode { get; set; }

        public SafetyMode()
        {
            this.mode = 0;
        }

        public SafetyMode(byte mode)
        {
            this.mode = mode;
        }
    }
}
#endif
